bases:
  - ../../base

namePrefix: dev-

commonLabels:
  env: dev

#Update Replica count
patches:
  - client-replica.yaml
  - server-replica.yaml

#Seperate Namespace
resources:
  - namespace.yaml

namespace: dev
